import './globals.css';
import { ToastContainer } from 'react-toastify';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={` antialiased`}>
        <div className='max-w-7xl mx-auto'>
          <div className='lg:mb-10 lg:mt-20'>
            {children}
            <ToastContainer />
          </div>
        </div>
      </body>
    </html>
  );
}
