import localFont from 'next/font/local';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={` antialiased`}>
        <div className='max-w-7xl mx-auto'>
          <div className='lg:mb-10 lg:mt-20'>{children}</div>
        </div>
      </body>
    </html>
  );
}
